export {
  calculateIndicativeIncomeBasedMonthlyPayment,
  calculateDuoMonthlyPaymentAfterExtraRepayment,
  calculateExtraRepaymentPayoffImpact,
  calculateExtraRepaymentVsInvesting,
  calculatePayoffDate,
  calculateRemainingMonthsToPayOff,
  calculateRemainingDebtAfterExtraRepayment,
  calculateStatutoryDuoMonthlyPayment,
  determineRelevantDuoPayment,
  sanitizeDuoMoney,
  sanitizeDuoPercent,
} from "@/lib/duo/calculations";
export type {
  DuoIncomeBasedMonthlyPaymentResult,
  DuoIncomeBasedInput,
  DuoMonthlyPaymentAfterExtraRepaymentInput,
  DuoPayoffTimingInput,
  DuoPayoffTimingResult,
  DuoPaymentSource,
  DuoRelevantPaymentInput,
  DuoRepaymentInput,
  DuoSituation,
  ExtraRepaymentPayoffImpactInput,
  ExtraRepaymentPayoffImpactResult,
  ExtraRepaymentStrategy,
  ExtraRepaymentVsInvestingInput,
  RelevantDuoPaymentResult,
  RepaymentRule,
} from "@/lib/duo/types";
